id: DFE6749F5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-05T06:52:52+00:00'
last_modified: '2022-05-26T12:04:14.952418+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    e7bf:
      image_group_id: I1PD95882
      title: འཇམ་དཔལ་རྡོ་རྗེ་བློ་གྲོས་འཕེལ་བ།
      total_pages: 1379
      order: 37
      base_file: e7bf.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
