id: P440104E0
initial_creation_type: ocr
source_metadata:
  volumes:
    c73d6591a6684d44bade938164fa2b09:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཇམ་དཔལ་རྡོ་རྗེ་བློ་གྲོས་འཕེལ་བ།
      total_pages: 1379
      volume_number: 37
